import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'AWS Web Application Framework API',
      version: '1.0.0',
      description: 'REST API for the AWS Web Application Framework with metadata-driven CRUD operations',
      contact: {
        name: 'API Support',
        email: 'support@example.com'
      },
      license: {
        name: 'MIT',
        url: 'https://opensource.org/licenses/MIT'
      }
    },
    servers: [
      {
        url: 'http://localhost:3000',
        description: 'Local development server'
      },
      {
        url: 'https://staging-api.example.com',
        description: 'Staging server'
      },
      {
        url: 'https://api.example.com',
        description: 'Production server'
      }
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT token obtained from Keycloak authentication'
        }
      },
      schemas: {
        FieldDatatype: {
          type: 'string',
          enum: ['text', 'text_area', 'single_select', 'multi_select', 'date', 'time', 'datetime', 'number', 'boolean', 'email', 'url'],
          description: 'Supported field data types'
        },
        ValidationType: {
          type: 'string',
          enum: ['required', 'min_length', 'max_length', 'pattern', 'min_value', 'max_value', 'email', 'url', 'custom'],
          description: 'Supported validation rule types'
        },
        ValidationRule: {
          type: 'object',
          properties: {
            type: {
              $ref: '#/components/schemas/ValidationType'
            },
            value: {
              description: 'Value for the validation rule (e.g., max length)',
              oneOf: [
                { type: 'string' },
                { type: 'number' },
                { type: 'boolean' }
              ]
            },
            message: {
              type: 'string',
              description: 'Custom error message'
            },
            customFunction: {
              type: 'string',
              description: 'Reference to custom validation function'
            }
          },
          required: ['type']
        },
        FieldDefinition: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              description: 'Unique identifier (generated by system)'
            },
            shortName: {
              type: 'string',
              description: 'Internal identifier (e.g., "user_email")',
              example: 'user_email'
            },
            displayName: {
              type: 'string',
              description: 'User-facing label',
              example: 'Email Address'
            },
            description: {
              type: 'string',
              description: 'Help text for users',
              example: 'User email address for login and notifications'
            },
            datatype: {
              $ref: '#/components/schemas/FieldDatatype'
            },
            datatypeProperties: {
              type: 'object',
              description: 'Type-specific configuration',
              additionalProperties: true,
              example: { displayMode: 'dropdown', options: ['Option 1', 'Option 2'] }
            },
            mandatory: {
              type: 'boolean',
              description: 'Whether field is required',
              default: false
            },
            validationRules: {
              type: 'array',
              items: {
                $ref: '#/components/schemas/ValidationRule'
              },
              description: 'Optional validation rules'
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
              description: 'Creation timestamp'
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
              description: 'Last update timestamp'
            }
          },
          required: ['shortName', 'displayName', 'description', 'datatype', 'datatypeProperties', 'mandatory']
        },
        ObjectFieldReference: {
          type: 'object',
          properties: {
            fieldShortName: {
              type: 'string',
              description: 'Reference to FieldDefinition short name',
              example: 'user_email'
            },
            mandatory: {
              type: 'boolean',
              description: 'Override field default mandatory setting',
              default: false
            },
            order: {
              type: 'integer',
              description: 'Display order in forms',
              example: 1
            }
          },
          required: ['fieldShortName', 'mandatory', 'order']
        },
        WizardStep: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              description: 'Step name',
              example: 'Basic Information'
            },
            description: {
              type: 'string',
              description: 'Step description',
              example: 'Enter basic user information'
            },
            fields: {
              type: 'array',
              items: {
                type: 'string'
              },
              description: 'Field short names to display in this step',
              example: ['user_name', 'user_email']
            },
            order: {
              type: 'integer',
              description: 'Step order',
              example: 1
            }
          },
          required: ['name', 'description', 'fields', 'order']
        },
        WizardConfiguration: {
          type: 'object',
          properties: {
            steps: {
              type: 'array',
              items: {
                $ref: '#/components/schemas/WizardStep'
              }
            }
          },
          required: ['steps']
        },
        FieldGroup: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              description: 'Group display name',
              example: 'Contact Information'
            },
            description: {
              type: 'string',
              description: 'Group description/help text',
              example: 'Enter customer contact details'
            },
            fields: {
              type: 'array',
              items: {
                type: 'string'
              },
              description: 'Field short names to include in this group',
              example: ['customer_email', 'customer_phone']
            },
            order: {
              type: 'integer',
              description: 'Display order of groups',
              example: 1
            }
          },
          required: ['name', 'description', 'fields', 'order']
        },
        ObjectDefinition: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              description: 'Unique identifier (generated by system)'
            },
            shortName: {
              type: 'string',
              description: 'Internal identifier (e.g., "customer")',
              example: 'customer'
            },
            displayName: {
              type: 'string',
              description: 'User-facing label',
              example: 'Customer'
            },
            description: {
              type: 'string',
              description: 'Description of this entity',
              example: 'Customer information and contact details'
            },
            fields: {
              type: 'array',
              items: {
                $ref: '#/components/schemas/ObjectFieldReference'
              },
              description: 'Fields that make up this object'
            },
            displayProperties: {
              type: 'object',
              properties: {
                defaultSortField: {
                  type: 'string',
                  description: 'Field to sort by in table views',
                  example: 'name'
                },
                defaultSortOrder: {
                  type: 'string',
                  enum: ['asc', 'desc'],
                  description: 'Sort direction',
                  example: 'asc'
                },
                searchableFields: {
                  type: 'array',
                  items: {
                    type: 'string'
                  },
                  description: 'Fields to include in search',
                  example: ['name', 'email']
                },
                tableColumns: {
                  type: 'array',
                  items: {
                    type: 'string'
                  },
                  description: 'Fields to show in table view',
                  example: ['name', 'email', 'phone']
                }
              }
            },
            wizardConfig: {
              $ref: '#/components/schemas/WizardConfiguration'
            },
            fieldGroups: {
              type: 'array',
              items: {
                $ref: '#/components/schemas/FieldGroup'
              },
              description: 'Optional field groupings for UI organization'
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
              description: 'Creation timestamp'
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
              description: 'Last update timestamp'
            }
          },
          required: ['shortName', 'displayName', 'description', 'fields', 'displayProperties']
        },
        FieldError: {
          type: 'object',
          properties: {
            field: {
              type: 'string',
              description: 'Field name that failed validation',
              example: 'email'
            },
            message: {
              type: 'string',
              description: 'Error message',
              example: 'Email is required'
            },
            value: {
              description: 'Invalid value provided',
              example: ''
            }
          },
          required: ['field', 'message']
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            error: {
              type: 'object',
              properties: {
                code: {
                  type: 'string',
                  description: 'Error code',
                  enum: ['VALIDATION_ERROR', 'NOT_FOUND', 'UNAUTHORIZED', 'FORBIDDEN', 'DUPLICATE_ERROR', 'CONSTRAINT_ERROR', 'INTERNAL_ERROR'],
                  example: 'VALIDATION_ERROR'
                },
                message: {
                  type: 'string',
                  description: 'Error message',
                  example: 'Validation failed'
                },
                details: {
                  type: 'array',
                  items: {
                    $ref: '#/components/schemas/FieldError'
                  },
                  description: 'Field-level error details'
                }
              },
              required: ['code', 'message']
            }
          }
        },
        ListResponse: {
          type: 'object',
          properties: {
            data: {
              type: 'array',
              items: {
                type: 'object',
                additionalProperties: true
              },
              description: 'Array of instances'
            },
            pagination: {
              type: 'object',
              properties: {
                page: {
                  type: 'integer',
                  description: 'Current page number',
                  example: 1
                },
                pageSize: {
                  type: 'integer',
                  description: 'Items per page',
                  example: 20
                },
                totalItems: {
                  type: 'integer',
                  description: 'Total number of items',
                  example: 100
                },
                totalPages: {
                  type: 'integer',
                  description: 'Total number of pages',
                  example: 5
                }
              },
              required: ['page', 'pageSize', 'totalItems', 'totalPages']
            }
          },
          required: ['data', 'pagination']
        }
      }
    },
    security: [
      {
        bearerAuth: []
      }
    ]
  },
  apis: ['./src/routes/*.ts', './src/index.ts']
};

export const swaggerSpec = swaggerJsdoc(options);
