#!/usr/bin/env bash
#
# Bring the whole platform up on this machine.
#
#   sudo ./scripts/deploy/bootstrap.sh
#
# Idempotent: safe to run again after a reboot, a code update, or a failed
# attempt. It generates secrets once and reuses them, because the Keycloak realm
# is imported on first start and *ignored* thereafter — regenerating them later
# would leave the realm holding one set and the backend using another, which
# presents as "sign-in works but every API call is 401".
#
# See docs/DEPLOY_SINGLE_INSTANCE.md.
set -euo pipefail

cd "$(dirname "$0")/../.."
ROOT="$PWD"
ENV_FILE="$ROOT/.env.deploy"
REALM_TEMPLATE="$ROOT/infrastructure/keycloak/realm-import.json"
REALM_STAMP="$ROOT/.deploy/realm-rendered"

COMPOSE="docker compose -f docker-compose.deploy.yml --env-file $ENV_FILE"
TOOLS="$COMPOSE --profile tools run --rm tools"

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m\n  ✖ %s\n\n\033[0m' "$*" >&2; exit 1; }

mkdir -p "$ROOT/.deploy"

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
log "Checking prerequisites"
command -v docker >/dev/null || die "Docker is not installed. See the user_data in terraform/environments/testing."
docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is missing."

# Building four Vite bundles is memory-hungry; a 2 GB box without swap gets
# killed part-way through with an error that blames esbuild rather than RAM.
TOTAL_MB=$(free -m 2>/dev/null | awk '/^Mem:/{print $2}' || echo 4096)
SWAP_MB=$(free -m 2>/dev/null | awk '/^Swap:/{print $2}' || echo 0)
if [ "$TOTAL_MB" -lt 3500 ] && [ "$SWAP_MB" -lt 1000 ]; then
  warn "${TOTAL_MB} MB RAM and no meaningful swap — the front-end build may be killed."
  warn "The Terraform for this environment adds 2 GB of swap; add some by hand if you did not use it."
fi

# ---------------------------------------------------------------------------
# 2. Configuration and secrets
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  log "Creating $ENV_FILE"

  [ -n "${PUBLIC_URL:-}" ]  || die "PUBLIC_URL is not set (e.g. https://test.example.com)."
  PUBLIC_HOST="${PUBLIC_HOST:-$(echo "$PUBLIC_URL" | sed -E 's#^https?://##; s#/.*##')}"

  secret() { openssl rand -hex 24; }

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The Keycloak secrets are baked into the imported realm — see the note at the
# top of that script before changing any of them.
PUBLIC_URL=$PUBLIC_URL
PUBLIC_HOST=$PUBLIC_HOST

DATABASE_NAME=aws_framework
DATABASE_USER=framework_user
DATABASE_PASSWORD=$(secret)

KEYCLOAK_REALM=aws-framework
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=$(secret)
KEYCLOAK_BACKEND_SECRET=$(secret)
KEYCLOAK_SERVICE_ACCOUNT_SECRET=$(secret)
KEYCLOAK_PASSWORD_CHECK_SECRET=$(secret)
KEYCLOAK_MEM_LIMIT=${KEYCLOAK_MEM_LIMIT:-1200m}

AWS_REGION=${AWS_REGION:-eu-west-1}
SES_FROM_EMAIL=${SES_FROM_EMAIL:-noreply@example.com}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}

LOG_LEVEL=info
# Where the web container publishes. The AWS instance sets this to a loopback
# port so the host's nginx can terminate TLS in front of it.
WEB_PUBLISH=${WEB_PUBLISH:-80}
EOF
  chmod 600 "$ENV_FILE"
  echo "  secrets generated; $ENV_FILE is readable only by root"
else
  echo "  $ENV_FILE exists — leaving it and its secrets alone"
fi

set -a; . "$ENV_FILE"; set +a

# ---------------------------------------------------------------------------
# 3. Render the realm
# ---------------------------------------------------------------------------
# The import file carries placeholders so it can live in the repository without
# secrets in it. Rendered once, next to the template, and never again: Keycloak
# reads it only when the realm does not yet exist, so a second render would
# quietly diverge from what is actually running.
if [ ! -f "$REALM_STAMP" ]; then
  log "Rendering the Keycloak realm"
  RENDERED="$ROOT/infrastructure/keycloak/realm-import.rendered.json"
  sed -e "s#PUBLIC_URL_PLACEHOLDER#${PUBLIC_URL}#g" \
      -e "s#BACKEND_SECRET_PLACEHOLDER#${KEYCLOAK_BACKEND_SECRET}#g" \
      -e "s#SERVICE_ACCOUNT_SECRET_PLACEHOLDER#${KEYCLOAK_SERVICE_ACCOUNT_SECRET}#g" \
      -e "s#PASSWORD_CHECK_SECRET_PLACEHOLDER#${KEYCLOAK_PASSWORD_CHECK_SECRET}#g" \
      "$REALM_TEMPLATE" > "$RENDERED"

  grep -q PLACEHOLDER "$RENDERED" && die "A placeholder survived rendering — check $RENDERED."

  # 0640, not 0600.
  #
  # This file holds client secrets, so it must not be world-readable — but
  # Keycloak has to *read* it, and it runs as uid 1000 inside its container.
  # At 0600 owned by root the container gets AccessDeniedException on it and
  # crash-loops, which presents as every /auth/* request returning 502 and
  # nothing on the box looking wrong.
  #
  # The container's gid is 0, so group-readable is exactly enough: Keycloak can
  # read it, and no ordinary user on the host can.
  chmod 640 "$RENDERED"
  touch "$REALM_STAMP"
  echo "  rendered for $PUBLIC_URL"
else
  echo "  realm already rendered — leaving it alone"
fi

# ---------------------------------------------------------------------------
# 4. Build and start
# ---------------------------------------------------------------------------
log "Building images (a few minutes on a small instance)"
$COMPOSE build

log "Starting Postgres and Keycloak"
$COMPOSE up -d postgres keycloak

echo -n "  waiting for Keycloak"
for _ in $(seq 1 90); do
  if $COMPOSE exec -T keycloak /bin/sh -c \
      'exec 3<>/dev/tcp/localhost/8080 && echo -e "GET /auth/health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && cat <&3' \
      2>/dev/null | grep -q '"status": *"UP"'; then
    echo " ready"; break
  fi
  echo -n "."; sleep 4
done

# ---------------------------------------------------------------------------
# 5. Migrations
# ---------------------------------------------------------------------------
# The `tools` service, not the production one: that image installs
# `--only=production` and has neither `node-pg-migrate` (a devDependency) nor
# the seed scripts.
log "Running database migrations"
$TOOLS npx node-pg-migrate up -m migrations

# ---------------------------------------------------------------------------
# 6. The rest of the stack
# ---------------------------------------------------------------------------
log "Starting the API and the web front ends"
$COMPOSE up -d

# ---------------------------------------------------------------------------
# 7. Optional demo data
# ---------------------------------------------------------------------------
# Off by default: it deletes every application row before it writes. The seed
# refuses to run against a non-local database or Keycloak, and both are local to
# this box (`postgres` and `keycloak` are in its allow-list), so it works here.
if [ "${SEED_DEMO_DATA:-false}" = "true" ]; then
  log "Seeding demo data (this DELETES existing application data)"
  $TOOLS npm run seed:demo -- --reset --no-stripe
fi

# ---------------------------------------------------------------------------
# 8. Report
# ---------------------------------------------------------------------------
log "Up"
cat <<EOF
  Member portal          ${PUBLIC_URL}/account
  Club administration    ${PUBLIC_URL}/orgadmin
  Platform admin         ${PUBLIC_URL}/admin
  Metadata repository    ${PUBLIC_URL}/metadata
  Keycloak console       ${PUBLIC_URL}/auth/admin/  (user: ${KEYCLOAK_ADMIN_USER})

  The Keycloak admin password is in ${ENV_FILE}, which is root-only.

  Logs:    docker compose -f docker-compose.deploy.yml --env-file ${ENV_FILE} logs -f
  Restart: docker compose -f docker-compose.deploy.yml --env-file ${ENV_FILE} restart
EOF

if [ -z "${STRIPE_SECRET_KEY:-}" ]; then
  warn "No Stripe key set — checkout will refuse. Add test keys to ${ENV_FILE} and restart the backend."
fi
